/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import regraNegocio.BebidaRN;
import vo.BebidaVO;

/**
 *
 * @author Karpa
 */
public class ModuloBebida extends TemplateBotoes implements ActionListener {

    /**
     * Creates new form ModuloBebida
     */
    int editar;
    TemplatePrincipal templatePrincipal;
    
    public ModuloBebida(TemplatePrincipal templatePrincipal) {
        this.templatePrincipal = templatePrincipal;
        initComponents();
        popularTabela();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPainel = new javax.swing.JPanel();
        lMarca = new javax.swing.JLabel();
        lTipo = new javax.swing.JLabel();
        lVolume = new javax.swing.JLabel();
        lPreco = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox();
        ftfPreco = new javax.swing.JFormattedTextField();
        tfMarca = new javax.swing.JTextField();
        tfVolume = new javax.swing.JTextField();
        lMl = new javax.swing.JLabel();
        spBebida = new javax.swing.JScrollPane();
        tBebida = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bebidas");
        setMinimumSize(new java.awt.Dimension(600, 450));
        setPreferredSize(new java.awt.Dimension(600, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pPainel.setPreferredSize(new java.awt.Dimension(600, 500));

        lMarca.setText("Marca:");

        lTipo.setText("Tipo:");

        lVolume.setText("Volume:");

        lPreco.setText("Preço:");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Água", "Suco", "Refrigerante", "Cerveja", "Vinho", "Caipiras", "Destilados" }));
        cbTipo.setEnabled(false);

        ftfPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        ftfPreco.setEnabled(false);

        tfMarca.setEnabled(false);

        tfVolume.setEnabled(false);

        lMl.setText("mL");

        tBebida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Marca", "Tipo", "Volume (mL)", "Preço (R$)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tBebida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tBebidaMouseClicked(evt);
            }
        });
        spBebida.setViewportView(tBebida);

        javax.swing.GroupLayout pPainelLayout = new javax.swing.GroupLayout(pPainel);
        pPainel.setLayout(pPainelLayout);
        pPainelLayout.setHorizontalGroup(
            pPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spBebida, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                    .addGroup(pPainelLayout.createSequentialGroup()
                        .addComponent(lMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMarca))
                    .addGroup(pPainelLayout.createSequentialGroup()
                        .addGroup(pPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pPainelLayout.createSequentialGroup()
                                .addComponent(lTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lVolume)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lMl))
                            .addGroup(pPainelLayout.createSequentialGroup()
                                .addComponent(lPreco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pPainelLayout.setVerticalGroup(
            pPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMarca)
                    .addComponent(tfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTipo)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lVolume)
                    .addComponent(tfVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lMl))
                .addGap(18, 18, 18)
                .addGroup(pPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPreco)
                    .addComponent(ftfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(spBebida, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pPainel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tBebidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tBebidaMouseClicked
        
        try{
        popularCampos();
        esconderCampos();
        
        }catch (Exception exc) {

            JOptionPane.showMessageDialog(null, "Tabela está desabilitada", "Cadastro Bebida", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tBebidaMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        templatePrincipal.setEnabled(true);
        templatePrincipal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbTipo;
    private javax.swing.JFormattedTextField ftfPreco;
    private javax.swing.JLabel lMarca;
    private javax.swing.JLabel lMl;
    private javax.swing.JLabel lPreco;
    private javax.swing.JLabel lTipo;
    private javax.swing.JLabel lVolume;
    private javax.swing.JPanel pPainel;
    private javax.swing.JScrollPane spBebida;
    private javax.swing.JTable tBebida;
    private javax.swing.JTextField tfMarca;
    private javax.swing.JTextField tfVolume;
    // End of variables declaration//GEN-END:variables

    @Override
    public void bNovoActionPerformed(ActionEvent e) {
        
        editar = 0;
        limpaCampos();
        mostrarCampos();
        
        bNovo.setEnabled(false);
        bSalvar.setEnabled(true);
        bEditar.setEnabled(false);
        bExcluir.setEnabled(false);
        bCancelar.setEnabled(true);
        tBebida.setEnabled(false);
    }

    @Override
    public void bSalvarActionPerformed(ActionEvent e) {
        
        try{
            
            if (tfMarca.getText().trim().equals(null) ||cbTipo.getSelectedIndex()==0 ||tfVolume.getText().trim().equals(null)|| ftfPreco.getText().trim().equals(null)){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos", "Cadastro Bebida", JOptionPane.PLAIN_MESSAGE);
            }else{
            BebidaVO bebidaVO = new BebidaVO();
            
            if (editar == 1){
                bebidaVO.setCodigo(Integer.parseInt(tfCodigo.getText()));
            }
            
            bebidaVO.setMarca(tfMarca.getText());
            bebidaVO.setTipo((String) cbTipo.getSelectedItem());
            bebidaVO.setVolume(Integer.parseInt(tfVolume.getText()));
            bebidaVO.setPreco(ftfPreco.getText());

            BebidaRN bebidaRN = new BebidaRN();
            bebidaRN.salvarBebida(bebidaVO, editar);
            
            bNovo.setEnabled(true);
            bSalvar.setEnabled(false);
            bEditar.setEnabled(true);
            bExcluir.setEnabled(true);
            bCancelar.setEnabled(false);
            tBebida.setEnabled(true);
            esconderCampos();
            popularTabela();
            
            JOptionPane.showMessageDialog(null, "Item salvo com sucesso.", "Cadastro de Bebida", JOptionPane.INFORMATION_MESSAGE); 
            }
        
        } catch (SQLException sqle) {

            JOptionPane.showMessageDialog(null, "Erro: " + sqle.getMessage(), "Cadastro Bebida", JOptionPane.ERROR_MESSAGE);
        
        }  catch (Exception exc) {

            JOptionPane.showMessageDialog(null, "Erro: " + exc.getMessage(), "Cadastro Bebida", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void bEditarActionPerformed(ActionEvent e) {
        
        if (tfMarca.getText().trim().equals("")) {

            JOptionPane.showMessageDialog(null, "Selecione uma bebida.", "Editar Bebida", JOptionPane.WARNING_MESSAGE);

        } else{
            editar = 1;
            
            bNovo.setEnabled(false);
            bSalvar.setEnabled(true);
            bEditar.setEnabled(false);
            bExcluir.setEnabled(false);
            bCancelar.setEnabled(true);
            tBebida.setEnabled(false);
            mostrarCampos();
        }
    }

    @Override
    public void bExcluirActionPerformed(ActionEvent e) {
        
        try{
            
            int confirmacao;
            BebidaVO bebidaVO = new BebidaVO();
        
            confirmacao = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "Cadastro de Bebida", JOptionPane.YES_NO_OPTION);
                if (confirmacao == 0){

                bebidaVO.setCodigo(Integer.parseInt((String) tBebida.getValueAt(tBebida.getSelectedRow(), 0)));

                BebidaRN bebidaRN = new BebidaRN();
                bebidaRN.excluirBebida(bebidaVO);

                limpaCampos();
                popularTabela();
                JOptionPane.showMessageDialog(null, "Bebida excluída com sucesso!", "Cadastro de Bebida", JOptionPane.PLAIN_MESSAGE);
                }
                
        } catch (SQLException sqle) {

            JOptionPane.showMessageDialog(null, "Erro: " + sqle.getMessage(), "Exclusão Bebida", JOptionPane.ERROR_MESSAGE);
            
        } catch (ArrayIndexOutOfBoundsException aiobe) {

            JOptionPane.showMessageDialog(null, "Selecione uma bebida.", "Exclusão Bebida", JOptionPane.WARNING_MESSAGE);

        } catch (Exception exc) {

            JOptionPane.showMessageDialog(null, "Erro: " + exc.getMessage(), "Exclusão Bebida", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void bCancelarActionPerformed(ActionEvent e) {
        
        int confirmacao;
        confirmacao = JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar", "Cancelar", JOptionPane.YES_NO_OPTION);
        if (confirmacao == 0){
            
            bNovo.setEnabled(true);
            bSalvar.setEnabled(false);
            bEditar.setEnabled(true);
            bExcluir.setEnabled(true);
            bCancelar.setEnabled(false);
            tBebida.setEnabled(true);
            limpaCampos();
            esconderCampos();
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        switch (e.getActionCommand()){
            
            case "Novo":
                
                bNovoActionPerformed(e);
                break;
                
            case "Salvar":
                
                bSalvarActionPerformed(e);
                break;
                
            case "Editar":
                
                bEditarActionPerformed(e);
                break;
                
            case "Excluir":
                
                bExcluirActionPerformed(e);
                break;
                
            case "Cancelar":
                
                bCancelarActionPerformed(e);
                break;
        }
    }
    
    public void mostrarCampos(){
        
        tfMarca.setEnabled(true);
        cbTipo.setEnabled(true);
        tfVolume.setEnabled(true);
        ftfPreco.setEnabled(true);
    }
    
    public void esconderCampos(){
        
        tfMarca.setEnabled(false);
        cbTipo.setEnabled(false);
        tfVolume.setEnabled(false);
        ftfPreco.setEnabled(false);
    }
    
    public void limpaCampos(){
        
        tfCodigo.setText("");
        tfMarca.setText("");
        cbTipo.setSelectedIndex(0);
        tfVolume.setText("");
        ftfPreco.setText("");
    }
    
    public void popularCampos() {

        tfCodigo.setText((String) tBebida.getValueAt(tBebida.getSelectedRow(), 0));
        tfMarca.setText((String) tBebida.getValueAt(tBebida.getSelectedRow(), 1));
        cbTipo.getModel().setSelectedItem((String) tBebida.getValueAt(tBebida.getSelectedRow(), 2));
        tfVolume.setText((String) tBebida.getValueAt(tBebida.getSelectedRow(), 3));
        ftfPreco.setText((String) tBebida.getValueAt(tBebida.getSelectedRow(), 4));
    }
    
    public void popularTabela() {

        try {

            BebidaRN bebidaRN = new BebidaRN();

            ArrayList<BebidaVO> bebidas = bebidaRN.buscarBebidas();

            javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) tBebida.getModel();
            dtm.fireTableDataChanged();
            dtm.setRowCount(0);

            for (BebidaVO bebidaVO : bebidas) {

                String[] linha = {"" + bebidaVO.getCodigo(), "" + bebidaVO.getMarca(), "" + bebidaVO.getTipo(), "" + bebidaVO.getVolume(), "" + bebidaVO.getPreco()};
                dtm.addRow(linha);
            }

        } catch (SQLException sqle) {

            JOptionPane.showMessageDialog(null, "Erro: " + sqle.getMessage(), "Bebidas", JOptionPane.ERROR_MESSAGE);
            
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage(), "Bebidas", JOptionPane.ERROR_MESSAGE);
        }
    }
}
