/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import regraNegocio.PedidoRN;
import vo.BebidaVO;
import vo.BordaVO;
import vo.ClienteVO;
import vo.PedidoVO;
import vo.PizzaVO;
import visao.ModuloCliente;

/**
 *
 * @author Karpa
 */
public class ModuloPedido extends ModuloCliente {

    /**
     * Creates new form ModuloPedido
     */
    TemplatePrincipal templatePrincipal;
    
    public ModuloPedido(TemplatePrincipal templatePrincipal) {
        
        this.templatePrincipal = templatePrincipal;
        initComponents();
        popularSabor();
        popularBorda();
        popularBebida();
        criarData();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPainelNorte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pPainelLeste = new javax.swing.JPanel();
        pPrincipal = new javax.swing.JPanel();
        lData = new javax.swing.JLabel();
        ftfData = new javax.swing.JFormattedTextField();
        lValor = new javax.swing.JLabel();
        bFinalizar = new javax.swing.JButton();
        pPizza = new javax.swing.JPanel();
        lSabor = new javax.swing.JLabel();
        cbSabor1 = new javax.swing.JComboBox();
        cbSabor2 = new javax.swing.JComboBox();
        cbSabor3 = new javax.swing.JComboBox();
        lTamanho = new javax.swing.JLabel();
        cbTamanho = new javax.swing.JComboBox();
        lBorda = new javax.swing.JLabel();
        cbBorda = new javax.swing.JComboBox();
        lQtdePizza = new javax.swing.JLabel();
        tfQtdePizza = new javax.swing.JTextField();
        lValorPizza = new javax.swing.JLabel();
        bAddPizza = new javax.swing.JButton();
        lValor1 = new javax.swing.JLabel();
        cbPizza = new javax.swing.JCheckBox();
        pBebida = new javax.swing.JPanel();
        lMarca = new javax.swing.JLabel();
        lVolume = new javax.swing.JLabel();
        cbMarca = new javax.swing.JComboBox();
        cbVolume = new javax.swing.JComboBox();
        lQtdeBebida = new javax.swing.JLabel();
        tfQtdeBebida = new javax.swing.JTextField();
        lValorBebida = new javax.swing.JLabel();
        bAddBebida = new javax.swing.JButton();
        lMl = new javax.swing.JLabel();
        lValor2 = new javax.swing.JLabel();
        cbBebida = new javax.swing.JCheckBox();
        spItens = new javax.swing.JScrollPane();
        tItens = new javax.swing.JTable();
        lValorFinal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pedidos");
        setMinimumSize(new java.awt.Dimension(1100, 660));
        setPreferredSize(new java.awt.Dimension(1100, 660));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pPainelNorte.setMinimumSize(new java.awt.Dimension(949, 81));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("Pedido");

        javax.swing.GroupLayout pPainelNorteLayout = new javax.swing.GroupLayout(pPainelNorte);
        pPainelNorte.setLayout(pPainelNorteLayout);
        pPainelNorteLayout.setHorizontalGroup(
            pPainelNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPainelNorteLayout.createSequentialGroup()
                .addContainerGap(727, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(182, 182, 182))
        );
        pPainelNorteLayout.setVerticalGroup(
            pPainelNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPainelNorteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        getContentPane().add(pPainelNorte, java.awt.BorderLayout.PAGE_START);

        pPainelLeste.setMinimumSize(new java.awt.Dimension(0, 0));
        pPainelLeste.setPreferredSize(new java.awt.Dimension(515, 380));
        pPainelLeste.setLayout(new java.awt.BorderLayout());

        pPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pPrincipal.setPreferredSize(new java.awt.Dimension(500, 380));

        lData.setText("Data:");

        ftfData.setEditable(false);
        ftfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        lValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lValor.setForeground(new java.awt.Color(51, 153, 0));
        lValor.setText("TOTAL: R$");

        bFinalizar.setText("Finalizar Pedido");
        bFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFinalizarActionPerformed(evt);
            }
        });

        pPizza.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pizzas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        lSabor.setText("Sabores:");

        cbSabor1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sabor 1" }));

        cbSabor2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sabor 2" }));

        cbSabor3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sabor 3" }));

        lTamanho.setText("Tamanho:");

        cbTamanho.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Pequena", "Média", "Grande" }));
        cbTamanho.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTamanhoItemStateChanged(evt);
            }
        });

        lBorda.setText("Borda:");

        cbBorda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione" }));
        cbBorda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBordaActionPerformed(evt);
            }
        });

        lQtdePizza.setText("Qtde:");

        tfQtdePizza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfQtdePizzaFocusLost(evt);
            }
        });

        lValorPizza.setText("--");

        bAddPizza.setText("Adicionar ao Pedido");
        bAddPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddPizzaActionPerformed(evt);
            }
        });

        lValor1.setText("Valor: R$");

        javax.swing.GroupLayout pPizzaLayout = new javax.swing.GroupLayout(pPizza);
        pPizza.setLayout(pPizzaLayout);
        pPizzaLayout.setHorizontalGroup(
            pPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPizzaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPizzaLayout.createSequentialGroup()
                        .addGroup(pPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lSabor)
                            .addComponent(lTamanho))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pPizzaLayout.createSequentialGroup()
                                .addComponent(cbSabor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSabor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSabor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pPizzaLayout.createSequentialGroup()
                                .addComponent(cbTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lBorda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbBorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lQtdePizza)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfQtdePizza, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPizza))))
                    .addGroup(pPizzaLayout.createSequentialGroup()
                        .addComponent(lValor1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lValorPizza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bAddPizza)))
                .addContainerGap())
        );
        pPizzaLayout.setVerticalGroup(
            pPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPizzaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSabor)
                    .addComponent(cbSabor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSabor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSabor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTamanho)
                    .addComponent(lBorda)
                    .addComponent(cbBorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lQtdePizza)
                    .addComponent(tfQtdePizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPizza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lValorPizza)
                    .addComponent(bAddPizza)
                    .addComponent(lValor1)))
        );

        pBebida.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bebidas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        lMarca.setText("Marca:");

        lVolume.setText("Volume:");

        cbMarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione" }));
        cbMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMarcaActionPerformed(evt);
            }
        });

        cbVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVolumeActionPerformed(evt);
            }
        });

        lQtdeBebida.setText("Qtde:");

        tfQtdeBebida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfQtdeBebidaFocusLost(evt);
            }
        });

        lValorBebida.setText("--");

        bAddBebida.setText("Adicionar ao Pedido");
        bAddBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddBebidaActionPerformed(evt);
            }
        });

        lMl.setText("mL");

        lValor2.setText("Valor: R$");

        javax.swing.GroupLayout pBebidaLayout = new javax.swing.GroupLayout(pBebida);
        pBebida.setLayout(pBebidaLayout);
        pBebidaLayout.setHorizontalGroup(
            pBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBebidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lMarca)
                    .addComponent(lValor2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pBebidaLayout.createSequentialGroup()
                        .addComponent(cbMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lVolume)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lMl)
                        .addGap(18, 18, 18)
                        .addComponent(lQtdeBebida))
                    .addGroup(pBebidaLayout.createSequentialGroup()
                        .addComponent(lValorBebida)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAddBebida)
                    .addGroup(pBebidaLayout.createSequentialGroup()
                        .addComponent(tfQtdeBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBebida)))
                .addContainerGap())
        );
        pBebidaLayout.setVerticalGroup(
            pBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBebidaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMarca)
                    .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lVolume)
                    .addComponent(cbVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lQtdeBebida)
                    .addComponent(tfQtdeBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lMl)
                    .addComponent(cbBebida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lValorBebida)
                    .addComponent(bAddBebida)
                    .addComponent(lValor2)))
        );

        spItens.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Itens do pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        tItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Descrição", "Qtde.", "Valor(R$)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spItens.setViewportView(tItens);
        if (tItens.getColumnModel().getColumnCount() > 0) {
            tItens.getColumnModel().getColumn(0).setMinWidth(45);
            tItens.getColumnModel().getColumn(0).setPreferredWidth(45);
            tItens.getColumnModel().getColumn(0).setMaxWidth(45);
            tItens.getColumnModel().getColumn(2).setMinWidth(40);
            tItens.getColumnModel().getColumn(2).setPreferredWidth(40);
            tItens.getColumnModel().getColumn(2).setMaxWidth(40);
            tItens.getColumnModel().getColumn(3).setMinWidth(65);
            tItens.getColumnModel().getColumn(3).setPreferredWidth(65);
            tItens.getColumnModel().getColumn(3).setMaxWidth(65);
        }

        lValorFinal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lValorFinal.setForeground(new java.awt.Color(51, 153, 0));
        lValorFinal.setText("0");

        javax.swing.GroupLayout pPrincipalLayout = new javax.swing.GroupLayout(pPrincipal);
        pPrincipal.setLayout(pPrincipalLayout);
        pPrincipalLayout.setHorizontalGroup(
            pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPrincipalLayout.createSequentialGroup()
                .addGroup(pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pPrincipalLayout.createSequentialGroup()
                                .addComponent(lData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftfData, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lValorFinal))
                            .addComponent(pBebida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pPizza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spItens, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(pPrincipalLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(bFinalizar)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pPrincipalLayout.setVerticalGroup(
            pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spItens, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lData)
                    .addComponent(ftfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lValor)
                    .addComponent(lValorFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pPainelLeste.add(pPrincipal, java.awt.BorderLayout.WEST);

        getContentPane().add(pPainelLeste, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static int id;
    static String nome;
    private void bFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFinalizarActionPerformed

        int confirmacao;
        confirmacao = JOptionPane.showConfirmDialog(null, "Deseja finalizar o pedido?", "Pedido", JOptionPane.YES_NO_OPTION);
        if (confirmacao == 0){
            
            try{
            
                PedidoVO pedidoVO = new PedidoVO();
            
                pedidoVO.setIdcliente(id);
                pedidoVO.setCliente(nome);
                pedidoVO.setData(ftfData.getText());
                pedidoVO.setValor(lValorFinal.getText());
                
                PedidoRN pedidoRN = new PedidoRN();
                pedidoRN.salvarPedido(pedidoVO);

                JOptionPane.showMessageDialog(null, "Pedido finalizado", "Pedido", JOptionPane.PLAIN_MESSAGE);
                dispose();
            
        
            } catch (SQLException sqle) {

                JOptionPane.showMessageDialog(null, "Erro: " + sqle.getMessage(), "Cadastro Cliente", JOptionPane.ERROR_MESSAGE);

            }  catch (Exception exc) {

                JOptionPane.showMessageDialog(null, "Erro: " + exc.getMessage(), "Cadastro Cliente", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_bFinalizarActionPerformed

    private void bAddBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddBebidaActionPerformed
        if(!cbBebida.isSelected()){
            JOptionPane.showMessageDialog(null, "Cheque os itens antes de adicionar ao pedido", "Pedido", JOptionPane.PLAIN_MESSAGE);
        }else{
            
            javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) tItens.getModel();
            dtm.fireTableDataChanged();

            String[] linha = {"" + "Bebida", "" + cbMarca.getSelectedItem() + " " + cbVolume.getSelectedItem()+"mL" , "" + tfQtdeBebida.getText(), "" + lValorBebida.getText()};
            dtm.addRow(linha);
            
            String valorF = lValorFinal.getText().replace(",", ".");
            Float valF = Float.valueOf(valorF);
            String valor = lValorBebida.getText().replace(",", ".");
            Float val = Float.valueOf(valor);
            String vFinal = String.valueOf(valF + val);
     
            lValorFinal.setText(vFinal.replace(".", ","));
            JOptionPane.showMessageDialog(null, "Bebida adicionada", "Pedido", JOptionPane.PLAIN_MESSAGE);
            
            //cbMarca.setSelectedIndex(0);
            //cbVolume.setSelectedIndex(0);
            tfQtdeBebida.setText("");
            lValorBebida.setText("0");
            cbBebida.setSelected(false);
        }
        
    }//GEN-LAST:event_bAddBebidaActionPerformed

    private void bAddPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddPizzaActionPerformed
        
        if(!cbPizza.isSelected()){
            JOptionPane.showMessageDialog(null, "Cheque os itens antes de adicionar ao pedido", "Pedido", JOptionPane.PLAIN_MESSAGE);
        }else{
            
            javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) tItens.getModel();
            dtm.fireTableDataChanged();

            if ((cbSabor1.getSelectedItem() != "Sabor 1") && (cbSabor2.getSelectedItem() == "Sabor 2") && (cbSabor3.getSelectedItem() == "Sabor 3")){
                String[] linha = {"" + "Pizza", "" + cbSabor1.getSelectedItem() + " / " + cbTamanho.getSelectedItem() + " / " + cbBorda.getSelectedItem(), "" + tfQtdePizza.getText(), "" + lValorPizza.getText()};
                dtm.addRow(linha);
            }
            
            if ((cbSabor1.getSelectedItem() != "Sabor 1") && (cbSabor2.getSelectedItem() != "Sabor 2") && (cbSabor3.getSelectedItem() == "Sabor 3")){
                String[] linha = {"" + "Pizza", "" + cbSabor1.getSelectedItem() + " / " + cbSabor2.getSelectedItem() + " / " + cbTamanho.getSelectedItem() + " / " + cbBorda.getSelectedItem(), "" + tfQtdePizza.getText(), "" + lValorPizza.getText()};
                dtm.addRow(linha);
            }
            
            if ((cbSabor1.getSelectedItem() != "Sabor 1") && (cbSabor2.getSelectedItem() != "Sabor 2") && (cbSabor3.getSelectedItem() != "Sabor 3")){
                String[] linha = {"" + "Pizza", "" + cbSabor1.getSelectedItem() + " / " + cbSabor2.getSelectedItem() + " / " + cbSabor3.getSelectedItem() + " / " + cbTamanho.getSelectedItem() + " / " + cbBorda.getSelectedItem(), "" + tfQtdePizza.getText(), "" + lValorPizza.getText()};
                dtm.addRow(linha);
            }
            
            String valorF = lValorFinal.getText().replace(",", ".");
            Float valF = Float.valueOf(valorF);
            String valor = lValorPizza.getText().replace(",", ".");
            Float val = Float.valueOf(valor);
            String vFinal = String.valueOf(valF + val);
     
            lValorFinal.setText(vFinal.replace(".", ","));
            JOptionPane.showMessageDialog(null, "Pizza adicionada", "Pedido", JOptionPane.PLAIN_MESSAGE);
            
            cbSabor1.setSelectedIndex(0);
            cbSabor2.setSelectedIndex(0);
            cbSabor3.setSelectedIndex(0);
            cbTamanho.setSelectedIndex(0);
            //cbBorda.setSelectedIndex(0);
            tfQtdePizza.setText("");
            lValorPizza.setText("0");
            cbPizza.setSelected(false);
        }
    }//GEN-LAST:event_bAddPizzaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        templatePrincipal.setEnabled(true);
        templatePrincipal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void cbTamanhoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTamanhoItemStateChanged
        // TODO add your handling code here:
        String tamanho = ((String) cbTamanho.getSelectedItem());
        if (tamanho == "Pequena"){
            lValorPizza.setText("20,00");
        }
        if (tamanho == "Média"){
            lValorPizza.setText("30,00");
        }
        if (tamanho == "Grande"){
            lValorPizza.setText("40,00");
        }
    }//GEN-LAST:event_cbTamanhoItemStateChanged

    private void tfQtdePizzaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfQtdePizzaFocusLost
        
        String valor = lValorPizza.getText().replace(",", ".");
        Float val = Float.valueOf(valor);
        Float qtde = (Float.valueOf(tfQtdePizza.getText()));
        String vfinal = String.valueOf(val * qtde);
        lValorPizza.setText(vfinal.replace(".", ","));
    }//GEN-LAST:event_tfQtdePizzaFocusLost

    private void cbBordaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBordaActionPerformed
        valorBorda();
    }//GEN-LAST:event_cbBordaActionPerformed

    private void cbVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVolumeActionPerformed
        valorBebida();
    }//GEN-LAST:event_cbVolumeActionPerformed

    private void tfQtdeBebidaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfQtdeBebidaFocusLost
        
        String valor = lValorBebida.getText().replace(",", ".");
        Float val = Float.valueOf(valor);
        Float qtde = (Float.valueOf(tfQtdeBebida.getText()));
        String vfinal = String.valueOf(val * qtde);
        lValorBebida.setText(vfinal.replace(".", ","));
    }//GEN-LAST:event_tfQtdeBebidaFocusLost

    private void cbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMarcaActionPerformed
        popularVolume();
    }//GEN-LAST:event_cbMarcaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddBebida;
    private javax.swing.JButton bAddPizza;
    private javax.swing.JButton bFinalizar;
    private javax.swing.JCheckBox cbBebida;
    private javax.swing.JComboBox cbBorda;
    private javax.swing.JComboBox cbMarca;
    private javax.swing.JCheckBox cbPizza;
    private javax.swing.JComboBox cbSabor1;
    private javax.swing.JComboBox cbSabor2;
    private javax.swing.JComboBox cbSabor3;
    private javax.swing.JComboBox cbTamanho;
    private javax.swing.JComboBox cbVolume;
    private javax.swing.JFormattedTextField ftfData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lBorda;
    private javax.swing.JLabel lData;
    private javax.swing.JLabel lMarca;
    private javax.swing.JLabel lMl;
    private javax.swing.JLabel lQtdeBebida;
    private javax.swing.JLabel lQtdePizza;
    private javax.swing.JLabel lSabor;
    private javax.swing.JLabel lTamanho;
    private javax.swing.JLabel lValor;
    private javax.swing.JLabel lValor1;
    private javax.swing.JLabel lValor2;
    private javax.swing.JLabel lValorBebida;
    private javax.swing.JLabel lValorFinal;
    private javax.swing.JLabel lValorPizza;
    private javax.swing.JLabel lVolume;
    private javax.swing.JPanel pBebida;
    private javax.swing.JPanel pPainelLeste;
    private javax.swing.JPanel pPainelNorte;
    private javax.swing.JPanel pPizza;
    private javax.swing.JPanel pPrincipal;
    private javax.swing.JScrollPane spItens;
    private javax.swing.JTable tItens;
    private javax.swing.JTextField tfQtdeBebida;
    private javax.swing.JTextField tfQtdePizza;
    // End of variables declaration//GEN-END:variables

    private void popularSabor() {
        try {

            PedidoRN pedidoRN = new PedidoRN();

            ArrayList<PizzaVO> sabor = pedidoRN.popularSabor();
           
            for (PizzaVO pizzaVO : sabor) {
                cbSabor1.addItem(pizzaVO.getSabor());
                cbSabor2.addItem(pizzaVO.getSabor());
                cbSabor3.addItem(pizzaVO.getSabor());
            }

        } catch (SQLException sqle) {

            JOptionPane.showMessageDialog(null, "Erro: " + sqle.getMessage(), "Pedido", JOptionPane.ERROR_MESSAGE);
            
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage(), "Pedido", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    private void popularBorda() {
        try {

            PedidoRN pedidoRN = new PedidoRN();

            ArrayList<BordaVO> borda = pedidoRN.popularBorda();
           
            for (BordaVO bordaVO : borda) {
                cbBorda.addItem(bordaVO.getSabor());
            }

        } catch (SQLException sqle) {

            JOptionPane.showMessageDialog(null, "Erro: " + sqle.getMessage(), "Pedido", JOptionPane.ERROR_MESSAGE);
            
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage(), "Pedido", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    private void popularBebida() {
        try {

            PedidoRN pedidoRN = new PedidoRN();

            ArrayList<BebidaVO> bebida = pedidoRN.popularBebida();
           
            for (BebidaVO bebidaVO : bebida) {
                cbMarca.addItem(bebidaVO.getMarca());
            }

        } catch (SQLException sqle) {

            JOptionPane.showMessageDialog(null, "Erro: " + sqle.getMessage(), "Pedido", JOptionPane.ERROR_MESSAGE);
            
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage(), "Pedido", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void valorBorda() {
        
        String borda = (String) cbBorda.getSelectedItem();
        try {

            PedidoRN pedidoRN = new PedidoRN();
            String preco = pedidoRN.valorBorda(borda);
           
            String valor = lValorPizza.getText().replace(",", ".");
            String replace = preco.replace(",", ".");
            Float val = Float.valueOf(valor);
            Float valBorda = Float.valueOf(replace);
            String vfinal = String.valueOf(val + valBorda);
            lValorPizza.setText(vfinal.replace(".", ","));
            

        } catch (SQLException sqle) {

            JOptionPane.showMessageDialog(null, "Erro: " + sqle.getMessage(), "Pedido", JOptionPane.ERROR_MESSAGE);
            
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage(), "Pedido", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void valorBebida() {
        
        String bebida = (String) cbMarca.getSelectedItem();
        String volume = (String) cbVolume.getSelectedItem();
        try {

            PedidoRN pedidoRN = new PedidoRN();
            String preco = pedidoRN.valorBebida(bebida, volume);
           
            String replace = preco.replace(".", ",");
            lValorBebida.setText(replace);
            

        } catch (SQLException sqle) {

            JOptionPane.showMessageDialog(null, "Erro: " + sqle.getMessage(), "Pedido", JOptionPane.ERROR_MESSAGE);
            
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage(), "Pedido", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void popularVolume() {
        
        cbVolume.removeAllItems(); 
        String marca = (String) cbMarca.getSelectedItem();
        try {

            PedidoRN pedidoRN = new PedidoRN();

            ArrayList<BebidaVO> volume = pedidoRN.popularVolume(marca);
           
            for (BebidaVO bebidaVO : volume) {
                cbVolume.addItem(String.valueOf(bebidaVO.getVolume()));
            }

        } catch (SQLException sqle) {

            JOptionPane.showMessageDialog(null, "Erro: " + sqle.getMessage(), "Pedido", JOptionPane.ERROR_MESSAGE);
            
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage(), "Pedido", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void criarData() {
        
        Date data = new Date();
        SimpleDateFormat formataData = new SimpleDateFormat("dd/MM/yy");
        
        ftfData.setText(formataData.format(data));
    }
    
    static void pegarCliente(PedidoVO pedidoVO) {
        
        nome = pedidoVO.getCliente();
        id = pedidoVO.getIdcliente();
    }

}
