/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Karpa
 */
public abstract class TemplateBotoes extends javax.swing.JFrame {

    /**
     * Creates new form FormTemplate
     */
    public TemplateBotoes() {
        initComponents();
        
        bNovo.addActionListener((ActionListener) this);
        bSalvar.addActionListener((ActionListener) this);
        bEditar.addActionListener((ActionListener) this);
        bExcluir.addActionListener((ActionListener) this);
        bCancelar.addActionListener((ActionListener) this);
    }
    
    public abstract void bNovoActionPerformed(ActionEvent e);//metodo abstrato
    public abstract void bSalvarActionPerformed(ActionEvent e);
    public abstract void bEditarActionPerformed(ActionEvent e);
    public abstract void bExcluirActionPerformed(ActionEvent e);
    public abstract void bCancelarActionPerformed(ActionEvent e);
    
    
    public void ActionPerformed (ActionEvent e){
        
        switch (e.getActionCommand()){
            
            case "Novo":
                
                bNovoActionPerformed(e);
                break;
                
            case "Salvar":
                
                bSalvarActionPerformed(e);
                break;
                
            case "Editar":
                
                bEditarActionPerformed(e);
                break;
                
            case "Excluir":
                
                bExcluirActionPerformed(e);
                break;
                
            case "Cancelar":
                
                bCancelarActionPerformed(e);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        psTemplate = new javax.swing.JPanel();
        bNovo = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        bExcluir = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        sSeparador = new javax.swing.JSeparator();
        bSalvar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lCodigo = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizzaria");

        psTemplate.setName("PainelSul"); // NOI18N
        psTemplate.setPreferredSize(new java.awt.Dimension(348, 70));

        bNovo.setText("Novo");

        bEditar.setText("Editar");

        bExcluir.setText("Excluir");

        bCancelar.setText("Cancelar");
        bCancelar.setEnabled(false);

        bSalvar.setText("Salvar");
        bSalvar.setEnabled(false);

        javax.swing.GroupLayout psTemplateLayout = new javax.swing.GroupLayout(psTemplate);
        psTemplate.setLayout(psTemplateLayout);
        psTemplateLayout.setHorizontalGroup(
            psTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psTemplateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(psTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(psTemplateLayout.createSequentialGroup()
                        .addComponent(sSeparador)
                        .addContainerGap())
                    .addGroup(psTemplateLayout.createSequentialGroup()
                        .addComponent(bNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))))
        );
        psTemplateLayout.setVerticalGroup(
            psTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psTemplateLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(sSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(psTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEditar)
                    .addComponent(bSalvar)
                    .addComponent(bNovo)
                    .addComponent(bExcluir)
                    .addComponent(bCancelar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(psTemplate, java.awt.BorderLayout.PAGE_END);

        lCodigo.setText("Código:");

        tfCodigo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(383, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCodigo)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton bCancelar;
    protected javax.swing.JButton bEditar;
    protected javax.swing.JButton bExcluir;
    protected javax.swing.JButton bNovo;
    protected javax.swing.JButton bSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lCodigo;
    private javax.swing.JPanel psTemplate;
    private javax.swing.JSeparator sSeparador;
    protected javax.swing.JTextField tfCodigo;
    // End of variables declaration//GEN-END:variables
}
